### ISSUE TITLE
Error en el registro. 

### ISSUE THREAD

**Issue by zarate10** [zarate10/EXAM-SYSTEM-TPO-AyED-I#1]
Al intentar registrar un nombre de usuario ya existente, la primera vez la validación anda bien, a partir del segundo intento permite registrar un nombre de usuario ya existente, esto desemboca en que se permita asignar una nueva contraseña, pudiendo acceder a la cuenta y sus datos.

Funciones involucradas en el error: 
```
def usuario_existe(new_user): 
    new_user += '.txt'
    # busca en el directorio de usuarios los archivos que contengan el nombre de usuario ingresado.
    for user in usuarios: 
        if user.name == new_user: 
            return True 

    return False
```
```
def validar_username():

    while True:
        new_user = input('Ingrese un nuevo usuario: ')
        
        if usuario_existe(new_user): 
            print('Usuario existente.')
            return False
        else: 
            return new_user
```

**Comment by SantiagoT81** [comment]
`import os 
import os.path

path_users = './db/usuarios'
usuarios = os.scandir(path_users)

def usuario_existe(new_user): 
    if os.path.isfile(f'{path_users}/{new_user}.txt'):
        return True
    else:
        return False

# ERROR, si colocamos dos veces un nombre utilizado lo admite
def validar_username():

    while True: 
        new_user = input('Ingrese un nuevo usuario: ')

        if not usuario_existe(new_user): 
            return new_user `

**Comment by SantiagoT81** [comment]
```
import os 
import os.path

path_users = './db/usuarios'
usuarios = os.scandir(path_users)

def usuario_existe(new_user): 
    if os.path.isfile(f'{path_users}/{new_user}.txt'):
        return True
    else:
        return False

# ERROR, si colocamos dos veces un nombre utilizado lo admite
def validar_username():

    while True: 
        new_user = input('Ingrese un nuevo usuario: ')

        if not usuario_existe(new_user): 
            return new_user 
```

**Comment by SantiagoT81** [comment]
Probé con el módulo "os.path" y creo que ahí funciona. Creo que con el anterior lo que hace es partir desde la última búsqueda que hizo y continuar, por eso es que siempre encuentra que es inexistente después de encontrar el anterior.

```
import os 
import os.path

path_users = './db/usuarios'
usuarios = os.scandir(path_users)

def usuario_existe(new_user): 
    if os.path.isfile(f'{path_users}/{new_user}.txt'):
        return True
    else:
        return False

# ERROR, si colocamos dos veces un nombre utilizado lo admite
def validar_username():

    while True: 
        new_user = input('Ingrese un nuevo usuario: ')

        if not usuario_existe(new_user): 
            return new_user 
```

**Comment by zarate10** [comment]
Cerrado

**Comment by zarate10** [comment]
Solucionado. Cerrado.
